### ISSUE TITLE
Torch 1.8.0 has no attribute 'set_deterministic'

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#6]
It seems that torch 1.8.0 does not use `set_deterministic` but use `use_deterministic_algorithms ` ([link](https://discuss.pytorch.org/t/use-deterministic-algorithms/118600)
```
Process Process-1:
Traceback (most recent call last):
  File "/n/home05/ztchen/.conda/envs/kdma/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home05/ztchen/.conda/envs/kdma/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home05/ztchen/KDMA/train_policy.py", line 77, in train
    utils.seed(seed)
  File "/n/home05/ztchen/KDMA/rl/utils.py", line 73, in seed
    torch.set_deterministic(True)
AttributeError: module 'torch' has no attribute 'set_deterministic'
```

However, after change `set_deterministic` to `use_deterministic_algorithms`, it throw me another error

```
Traceback (most recent call last):
  File "/n/home05/ztchen/.conda/envs/kdma/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home05/ztchen/.conda/envs/kdma/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home05/ztchen/KDMA/train_policy.py", line 104, in train
    actions, *args = agentAlgo.act(state, True)
  File "/n/home05/ztchen/KDMA/models/ppo.py", line 43, in act
    pi, v = self(state)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/n/home05/ztchen/KDMA/rl/actor_critic.py", line 151, in forward
    pi = self.model.actor(s, skip_header=True)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/n/home05/ztchen/KDMA/rl/actor_critic.py", line 165, in forward_actor
    return self.actor_forward(s)
  File "/n/home05/ztchen/KDMA/models/networks.py", line 89, in forward
    mu = self.model(agent, neighbors, self.n_neighbors)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/n/home05/ztchen/KDMA/models/networks.py", line 58, in forward
    y = self.model(self.embedding(agent, neighbors, n_neighbors))
  File "/n/home05/ztchen/KDMA/models/networks.py", line 49, in embedding
    x = self.neighbor_embedding(neighbors.view(-1, self.neighbor_dim)).sum(0)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/n/home05/ztchen/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
```

**Comment by xupei0610** [comment]
The API for the deterministic option in PyTorch changed frequently in recent versions and has some compatibility problems. A simple solution is just to comment the line of `torch.set_deterministic(True)` in `rl/utils.py` to ensure the code can run without exceptions.

**Comment by chenzhutian** [comment]
Yep I did. Another solution is to 
‘To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8.’

 For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
